### PR TITLE
ROO-3881: Fixing STS infinite loop after import Spring Roo multimodule project

### PR DESCRIPTION
**Pull request by jcagarcia**
Seems like when developers generates a multimodule project using the STS Spring Roo plugin, all modules are imported correctly.

However, if developer creates the multimodule project using Spring Roo from the OS Shell and after tries to import the project to the STS as existing maven project, an infinite loop appears freezing the computer.

This problem doesn't appears with single module projects.

To solve it, only parent modules should be define the Spring Roo nature. To identify if some module is parent or not i'm going to check if the parent project is Spring IO Platform and if it contains Spring Roo dependency. For multimodule projects, also I check if it has pom packaging. 

On the other hand, to identify the module that could be opened with the Spring Roo Shell, I've just created a RooProjectDecorator that will include the "[roo]" flag on the projects that have Spring Roo nature.

Spring Roo Decorator

### CODE REVIEW

**Comment by martinlippert** [comment]
If you add a new file, you should have your company mentioned as the copyright owner, not "GoPivotal, Inc." (in case it is truely new, not copied).

**Comment by jcagarcia** [comment]
I've just push a new commit to this pull-request indicating that the `RooProjectDecorator.java` class has been copied from the `BootProjectDecorator.java class` .

https://github.com/spring-projects/spring-ide/pull/93/commits/7bd498ec80ac9d12a31ae189b288fd26cbb3b80d

Regards,

**Comment by jcagarcia** [comment]
Thanks @martinlippert for your time :)

Much appreciated!!!

**Comment by martinlippert** [comment]
No problem at all, thanks a lot for YOUR work on the Roo support and your pull requests!!!

**Pull request merged**
