### PR TITLE
NamespaceHandler to support osgi blueprint 

### PR DESCRIPTION
**Pull request by amergey**
Here a proposal to fix https://issuetracker.springsource.com/browse/STS-4252

The code comes from a NamespaceHandler implementation I found in eclipse gemini.
I started to clean it, removing lot of code not necessary for IDE, then I fixed some bugs

### CODE REVIEW

**Comment by martinlippert** [comment]
That is great, thanks for the contribution. Please don't forget to sign the contributors license agreement here: https://support.springsource.com/spring_eclipsecla_committer_signup - thanks!!!

**Comment by amergey** [comment]
Done, do you need the confirmation number ?

**Comment by martinlippert** [comment]
No, I don't need the confirmation number, got that already via the system... :-) Thanks!!!

**Comment by martinlippert** [comment]
We are currently in the process of releasing a maintenance release for STS, but I will not be able to include your contribution in that (due to the pure size of the contribution). But I will definitely put this on the list for STS 3.7.3, ok?

**Comment by amergey** [comment]
No problem

**Comment by martinlippert** [comment]
Thanks again for the contribution!!!

Merged it into master to make this part of STS and Spring IDE 3.7.3. Will need to include this in the feature definition and create a pom.xml for the tycho build for it, but that is an easy thing to do.

**Pull request merged**
