### PR TITLE
IDE-1370: Updating Spring Roo plugin to work with Roo 2.0

### PR DESCRIPTION
**Pull request by jcagarcia**
Spring Roo 2.0 has change its project distribution and was updated to OSGi R5 and Felix 4.6.1 so Spring Roo STS Plugin needs to apply this updates to work.

https://jira.spring.io/browse/IDE-1370

Tested with Spring Roo 2.0 and previous version Spring Roo 1.3.1.RELEASE:
Spring Roo 2.0.0.BUILD-SNAPSHOT
Spring Roo 1.3.1.RELEASE

Regards,

### CODE REVIEW

**Comment by martinlippert** [comment]
I have a few minor little comments here:
- Can you remove the nightly distribution update site change again?
- Can you update the copyright header if you change files? (update the year, and maybe a line about your contribution at the end of the copyright statement)
That would be great!!!

I also have one more question: Does this change stop support for older < 1.3.1 versions of Roo? Just asking.

**Comment by jcagarcia** [comment]
Hi Martin,

I've just applied the changes you mentioned above!

* Nightly distribution URL has not been modified, I revert my changes on the next commit https://github.com/jcagarcia/spring-ide/commit/45a71a0a548c8cc86b0a98508f44fb82cd44cb31
* I've updated the copyright header with year and contributors...
* This changes were tested with the following ROO versions and works correctly. There's no reasons to fails with a previous one...
 * Spring Roo 1.2.5.RELEASE
 * Spring Roo 1.3.1.RELEASE
 * Spring Roo 2.0.0.BUILD-SNAPSHOT

If you have more comments, let me know!! :D

Best regards,

**Comment by martinlippert** [comment]
Thanks for incorporating my comments, merged the pull request. Please keep an eye on the builds:
- https://build.spring.io/browse/IDE-E43
- https://build.spring.io/browse/IDE-CONTINUOUSTESTING

**Comment by jcagarcia** [comment]
Perfect! Thank you so much!

When is going to be builded some STS-CI version to test my changes? Where can i found it?

Regards,

**Comment by martinlippert** [comment]
There are two options:

1.)
The Spring IDE build at https://build.spring.io/browse/IDE-E43 runs immediately after each push. It uploads the results to the Spring IDE nightly update site (http://dist.springframework.org/snapshot/IDE/nightly/). You can update an existing STS with those newer Spring IDE components by going to the "Install New Software" dialog, selecting the Spring IDE nightly update site, selecting the already installed components of Spring IDE, and press "Install". Eclipse/STS will notify you that the installation got changed automatically from installing new components to updating existing components.

2.)
The second option is to download a nightly distribution build of STS (http://dist.springsource.com/snapshot/STS/nightly-distributions.html) and to install the components you want to test in there manually via "Install New Software" or if they are already installed via "Check for Updates". So in your case, if you have an existing STS nightly build with Roo support installed into it, you should be able to add the nightly distribution update site (http://dist.springsource.com/snapshot/TOOLS/nightly/e4.4 for Eclipse 4.4, for example) and press "Check for Updates". This should do it. The nightly distribution download and update site is built once a day, so it might take a while until changes to Spring IDE are showing up in this distribution build. You can verify that your changes are in that build by downloading it and checking the version of the Spring IDE bundles in your plugins folder. The name contains the exact CI build number from https://build.spring.io/browse/IDE-DNE44.

Hope this helps!!!

**Comment by martinlippert** [comment]
One more comment: it is great to see you working on the STS and Eclipse integration for Spring Roo. To make your life easier in the future, it would also be possible to extract the STS Roo plugins into a separate GitHub repository (your own, a DISID organization repo, or something like that) with full commit rights for you. That way you could setup your own Maven tycho build for just those bundles, release them whenever it makes sense to you, and the STS team would consume the latest release from your update site for inclusion in the STS distribution update site and the STS dashboard. Just a thought. Let me know what you think about that. We can also chat about it offline.

**Comment by jcagarcia** [comment]
Hi Martin, 

I've been able to test my changes on a nightly distribution following your instructions.. thank you so much!! (I've found some little errors/changes that I will apply on a future pull request)

About to extract the STS Roo plugins into a separate GitHub repository I was speaking with DISID managers and they told me that when they had a meeting with Pivotal about Spring Roo leading, they agreed that all Spring Roo components will be located on Pivotal and Spring infrastructure... so, by the moment, they prefer to mantain STS Roo plugins into Spring GitHub repository.

On the other hand, they suggest if is possible that as member of GitHub spring-projects you (or anybody with the necessary role) could give me rights to commit on spring-ide project. Now, I have full commit rights on spring-roo project...

Regards,

**Comment by martinlippert** [comment]
As another option we could also move just the Roo related parts of the Spring IDE project in GitHub to a separate repository under the same organization (spring-projects) to give you more freedom. But that is just an option. We can also just continue in the same way as we do at the moment.

A side effect of this would be that the Roo plugins for Spring IDE would continue to be included in our milestone/release cycles/builds and that we would change version numbers to match the general Spring IDE process. Is that fine with you? You would also need to be aware of the release build/test/GA dates and work towards them as well. What do you think?

**Comment by jcagarcia** [comment]
Hi Martin, 

I've spoken with DISID managers and they told me that is better to maintain all STS components together in the same repository... So, if you don't have any inconvenience with that we can just continue in the same way as we do at the moment... Are you agree?

As always thank you for your support... and for your patience!!!

Regards,

**Comment by martinlippert** [comment]
Sure, we can continue in the same way as we do at the moment, no problem at all. If you want to get those components into separate repos one day in the future, just let me know.

**Comment by martinlippert** [comment]
Btw, are you monitoring questions on stackoverflow for Roo and the STS integration? Just came across this one: http://stackoverflow.com/questions/29836128/gwt-addon-doesnt-install-on-spring-roo-on-sts-command-web-gwt-setup-not-fou, maybe something for you to take a look at?

**Pull request merged**
