### PR TITLE
Updating roo supported version range

### PR DESCRIPTION
**Pull request by jcagarcia**
I've just modify Spring Roo version range... Spring Roo is growing up and we don't need any version range limitation on STS Roo Support :)

Regards,

### CODE REVIEW

**Comment by martinlippert** [comment]
Sounds good, will merge the pull request. Did you sign the CLA for Spring IDE already? https://support.springsource.com/spring_eclipsecla_committer_signup

Need that in order to merge the pull request and keep the license clean. Thanks!!!

**Comment by jcagarcia** [comment]
Hi martinlippert and thank you for your quick answer,

I've just signed CLA for Spring IDE.

Regards,

**Comment by martinlippert** [comment]
Thanks for signing the CLA, merged the pull request. Thanks for the contribution!!!

**Comment by jcagarcia** [comment]
Thanks for your quick answer and your collaboration!!

Best Regards,

**Pull request merged**
